defaults:
  - backend: transformers
type: "VLAPPOPolicy"
device: "cuda"
env_metadata: None
rollout_mode: "sync"
weight_buffer:
  type: "WeightBuffer" # WeightBuffer, CPUWeightBuffer, ShardedWeightBuffer
  buffer_strategy: "Double" # None, Double, Shared, Sharded
model_cfg:
  model_name: "openvla"
  model_path: "/data/ckpts/gen-robot/openvla-7b-rlvla-warmup"
  tokenizer_path: "/data/ckpts/gen-robot/openvla-7b-rlvla-warmup"
  action_dim: 7
  num_action_chunks: 1
  use_proprio: False
  unnorm_key: bridge_orig
  center_crop: True
  do_sample: False
  
  precision: "bf16"
  add_bias_linear: False
  add_qkv_bias: True
  vocab_size: 32000
  hidden_size: 4096
  add_value_head: True
  image_size: [224, 224]
  is_lora: True
  lora_rank: 32
  lora_alpha: 32
  ckpt_path: null
  use_wrist_image: False
  attn_implementation: "flash_attention_2"
  low_cpu_mem_usage: True
  trust_remote_code: True
  gradient_checkpointing: False
  # temporary fix, will be removed later
  max_prompt_length: 30

optim_cfg:
  # vla optimizer
  type: "AdamW"
  lr: 1.0e-4
  value_lr: 3.0e-3
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_eps: 1.0e-08
  weight_decay: 0.01
  grad_clip_norm: 10.0
  critic_warmup_steps: 0

ppo_cfg:
  # ppo
  entropy_bonus: 0
  clip_ratio: 0.2
  value_clip_ratio: 0.2
  huber_delta: 10.0
  
  gamma: 0.99
  gae_lambda: 0.95

  reward_type: action_level
  logprob_type: action_level
  entropy_type: action_level

  adv_type: gae
  loss_type: actor_critic
  loss_agg_func: "token-mean"

# params for rollout
sampling_params:
  do_sample: True
  temperature_train: 1.0
  temperature_eval: 0.6
  top_k: 0
  top_p: 1.0
  repetition_penalty: 1.0

# length argument for autoregressive sampling
# max length means max amount of tokens to generate
length_params:
  max_new_token: 7
  max_length: 1024
  min_length: 1

auto_reset: True