max_epochs: 1000
max_rollout_steps: 48
warm_up_rollout_steps: 16
batch_size: 1024 # not use 
mini_batch_size: 256
micro_batch_size: 32
update_epoch: 4
rollout_epoch: 1
eval_interval: 10
save_interval: 10
save_dir: ${log.log_dir}/${log.project}/${log.name}/weights

mode: "sync"