max_epochs: 1000
max_rollout_steps: 48
warm_up_rollout_steps: 32
batch_size: 4096 # not use
mini_batch_size: 2048
micro_batch_size: 128
update_epoch: 4
rollout_epoch: 8
eval_interval: -1
save_interval: -1
save_dir: ${log.log_dir}/${log.project}/${log.name}/weights

mode: "sync"