max_epochs: 400
max_rollout_steps: 160
max_eval_rollout_steps: 80
batch_size: 5120
mini_batch_size: 160
micro_batch_size: 8
eval_interval: 5
save_interval: 10
save_dir: ${log.log_dir}/${log.project}/${log.name}/weights
