defaults:
  - buffer: rollout_buffer
  - env: libero
  - train: train_tiny
  - policy: openpi_ppo
  - log: wandb
  - cluster: 1t1e
  - _self_

engine: syncrl
policy:
  optim_cfg:
    lr: 1.0e-6
buffer:
  capacity: 12288
log:
  name: tiny_exp